TRUNCATE TABLE items CASCADE;
ALTER SEQUENCE items_id_seq RESTART WITH 1;
INSERT INTO items (name) VALUES ('Ležaj');
INSERT INTO items (name) VALUES ('Plakar');
INSERT INTO items (name) VALUES ('Klima');
INSERT INTO items (name) VALUES ('Telefon');
INSERT INTO items (name) VALUES ('TV');
INSERT INTO items (name) VALUES ('Internet');
INSERT INTO items (name) VALUES ('Kuhinjski elementi');
INSERT INTO items (name) VALUES ('Mikrotalasna');
INSERT INTO items (name) VALUES ('Šporet');
INSERT INTO items (name) VALUES ('Rerna');
INSERT INTO items (name) VALUES ('Rešo');
INSERT INTO items (name) VALUES ('Frižider');
INSERT INTO items (name) VALUES ('Zamrzivač');
INSERT INTO items (name) VALUES ('Sudomašina');
INSERT INTO items (name) VALUES ('Veš mašina');
INSERT INTO items (name) VALUES ('Kancelarijski nameštaj');
INSERT INTO items (name) VALUES ('Terasa');
INSERT INTO items (name) VALUES ('Lođa');